---
title: The p-median Problem
output:
  html_document:
    mathjax: local
    self_contained: false
---





<h1>Statement of the Problem</h1>

The p-median problem is an application of linear optimization approaches with respect to a graph. Specifically,  it is a facility-location model with the purpose of locating $p$ facilities (hereafter referred to as vertices or nodes) to minimize a constraint equation based on weighted average distances between demand nodes and selection location nodes.

<p>
Stated more formally, given some graph $G=(V,E)$ where 
$$V=(v_1,\ldots,v_n: n \in \Bbb N)$$ is a set of nodes of $G$, each representing a demand weight, and where 
$$E=(e_1,\ldots,e_m: m \in \Bbb N)$$ is a set of connected nodes of $G$, the p-median problem seeks to find any number $p$ vertices such that the sum of the weighted distances from each vertex in $G$ to the closest facility is minimized. The lengths between each vertex and each facility is calculated by taking the absolute value of each member of $E$ that represents a successive path connection of nodes in between the two and computing their sum.
</p>

<p>
In this paper, we will be discussing how exactly this calculation is performed. Three sections will be covered:
<ul>
<li>Rectifying the Issue of Computational Complexity</li>
<li>Setting up the p-median Problem as a Linear Programming Problem</li>
<li>Finding a Solution to a Linear Programming Problem</li>
</ul>
</p>

<br>





<h1>Rectifying the Issue of Computational Complexity</h1>
Unfortunately, when attempting to perform optimization calculations for this problem using a general graph, the computation time is $\mathcal N \mathcal P$-hard. We can rectify this however by formulating the problem using a mathematical tree.

<p>
Given some graph $G=(V,E)$ where
$$V=(v_1,\ldots,v_n: n \in \Bbb N)$$
is a set of nodes of $G$, and where
$$E=(e_1,\ldots,e_m: m \in \Bbb N)$$ is a set of connected nodes of $G$, we call the graph $T=G$ a <b>tree</b> if it is undirected, connected, and contains no cycles. From the procedures detailed in (Benkoczi et al.)<sup><a href="#section1">[i]</a></sup>, if $T$ is a both rooted and binary tree, then an $O(nlog^{p+2}n)$ algorithm exists; thus, a solution to the p-median problem on $T$ can be computed in polynomial time.
</p>

<p>
If $T$ is not rooted, then it can be made to be so by arbitrarily selecting a vertex to designate as its root. If $T$ is not binary, then $T$ may be made to be binary by adding a linear number of vertices and edges to that set. Because it follows that any object that is composed of a linear function of objects that can be solved in polynomial time is itself solvable in polynomial time, then it follows that a tree $T$ which is neither rooted nor binary can also be solved in polynomial time.
</p>

<p>
Thus, because the graph $G$ for the p-median problem can be formulated as the tree $T=G$, it follows that we can calculate a solution for the p-median problem in polynomial time.
</p>

<br>





<h1>Setting up the p-median Problem as a Linear Programming Problem</h1>
<p>
Now that we have established that we can find a solution to the p-median problem in polynomial time by setting up the problem as a tree, we desire to formulate the p-median problem as a linear programming problem. The form for the general linear programming problem is as follows:
<blockquote>
Minimize
$$f(\mathbf X) = \sum_{i=1}^n c_i x_i \tag{1}\label{eq1}$$
subject to
$$\sum_{i=1}^n a_{ij} x_i = b_j \forall \ j=1,2,\ldots,m \tag{2}\label{eq2}$$
and 
$$x_i\ge 0, \forall \ i=1,2,\ldots,n \tag{3}\label{eq3}$$ where 
$$a_{ij},c_i \in \Bbb R \text{, } b_j \ge 0 \text{, and } m\lt n \tag{4}\label{eq4}$$
</blockquote>

<p>
We will first find the total cost as a function of any given collection of $p$ vertices from our set of nodes; we will refer to this function as the <b>objective function</b>. Once this is done, we will use this objective function to formulate the p-median problem in the form of the general linear programming problem. We divide these two procedures into two subsections.
</p>

<br>




<h2>Formulating the Objective Function</h2>

Let $T=G$ be as before, and let
$$F_p=(\mathscr f_1,\dots,\mathscr f_p:p\leq n \in \Bbb N)$$ be a collection of some $p$ vertices in $T$ which represent a potential facility-location set (hereafter referred to as <i>median set</i>) for $T$. Let
$$W=(w_1,\ldots,w_n:n \in \Bbb N)$$ be such that $w_i$ represents the weight for vertex $v_i \in V$; similarly, define
$$A=(a_1,\ldots,a_m:m \in \Bbb N)$$ to be the (tree-metric) distance<sup><a href="#section2">[ii]</a></sup> between adjacent vertices such that, if
$$e_k=(e_{k_1},e_{k_2})$$ where $e_{k_1},e_{k_2} \in V$, then
$$a_k=\lVert e_k\rVert=\lVert e_{k_1} - e_{k_2} \rVert,\forall \ e_k \in E$$


<p>
Let the distance between any two arbitrary vertices $v_i,v_j \in V$ be defined as the mapping $\delta:(v_i,v_j) \mapsto \delta(v_i,v_j)$, and then define the mapping $\psi:v_i \mapsto \psi(v_i)$ to be the minimum weighted distance between vertex $v_i$ and any facility within the potential median set; that is,
$$\psi(v_i)=w_i \cdot\min_{\mathscr f_z \in F_p} \delta (v_i,\mathscr f_z)$$ Finally, let the potential cost of locating a facility at the location $\mathscr f_z$ be defined as the mapping $\gamma:\mathscr f_z \mapsto \gamma(\mathscr f_z)$.
</p>

<p>
We are now ready to formulate our objective function for any given potential median set: we define the mapping $\Gamma: F_p \mapsto \Gamma(F_p)$ by
$$\Gamma(F_p)=\sum_{\mathscr f_z \in F_p} \gamma(\mathscr f_z) +\sum_{v_i \in V} \psi(v_i)$$
to be the objective function for any given potential median set $F_p \subseteq V$.
</p>

<br>





<h2>Creating the General Linear Programming Problem</h2>
Because we wish to select from any arbitrary potential median set the one for which the objective function is minimized, our goal in solving the p-median problem is to find the median set $\mathscr F_p$ such that 
$$\mathscr F_p = \min_{F_p \subseteq V} \Gamma (F_p)$$
We will show that, with a few adjustments in terminology and symbology, this $\mathscr F_p$ fits the form of $\eqref{eq1}$. 




<h3>Rearranging the Objective Function</h3>
<p>
Looking just at $\Gamma (F_p)$ alone, we have that our objective function is equal to 
$$\sum_{z=1}^p \gamma (\mathscr f_z) + \sum_{i=1}^n \psi (v_i)$$ then, using the fact that 
$$\psi (v_i) = w_i \cdot \min_{\mathscr f_z \in F_p} \delta (v_i,\mathscr f_z)$$ our objective function can be written as
$$\sum_{z=1}^p \gamma (\mathscr f_z) + \sum_{i=1}^n w_i \cdot \min_{\mathscr f_z \in F_p} \delta (v_i,\mathscr f_z)$$
</p>

To proceed any further, we need to formulate the two-variable function $\delta$ using known quantities given from the problem. For the first case, suppose the vertex in question is an element of the median set; that is, $v_i \in F_p$. If we now define the notation $$\delta (v_i, F_p) = \min_{\mathscr f_z \in F_p} \delta (v_i,\mathscr f_z)$$ 
then it follows that $\delta (v_i,F_p) = 0$. 
</p>

<p>
For all other cases, we suppose that $v_i \notin F_p$. Then, $\forall\ \mathscr f_z \in F_p$ because $T$ is connected, there exists some set $K \subset V$ such that every element $k \neq v_i \text{ and } k \neq \mathscr f_z$ in $K$ lies on a path connecting $v_i$ to $\mathscr f_z$; furthermore, because $T$ is acyclic, this path is <il>the</il> unique path connecting $v_i$ and $\mathscr f_z$. Before proceeding, let the mapping $\phi: (v_i, \mathscr f_z) \mapsto K$ formally define $K$ for a given $v_i,\mathscr f_z$ when the vertex and facility in question are ambiguous.
</p>

<p>
Let us denote the $q$ elements $k_q \in K$ to be such that 
$$k_q=\mathscr f_z \text{ and } \forall\ k_r\ |\ r = 1,2,\ldots,q-1,\  \exists\ e_{k_r} \in E\ |\ e_{k_r} = (k_r,k_{r+1})$$
Hence, each subset of vertices $K$ of $V$ defined in the above way induces a subset of edges $(e_{k_1},e_{k_2},\ldots,e_{k_{q-1}}) \subset E$. As before, we define the mapping $\Phi: K \mapsto \epsilon$ to formally define $\epsilon$ for a given $K$ for a given $v_i,\mathscr f_z$ by 
$$\epsilon = \Phi (K) = (\Phi \circ \phi)(v_i,\mathscr f_z)$$
which is composed of $q-1$ elements 
$$\epsilon_r = \Phi_r (k) = (\Phi \circ \phi)_r (v_i,\mathscr f_z)$$
We define one final mapping before proceeding: $\varepsilon: (v_i,\mathscr f_z,r) \mapsto \epsilon$ as 
$$\varepsilon_r (v_i,\mathscr f_z) = (\Phi \circ \phi)_r (v_i,\mathscr f_z)= \epsilon_r$$
</p>

<p>
Recall that the set $A$ is defined such that $\forall\ a_k \in A,\ \exists \text{ corresponding } e_k \in E$. Hence, being careful about our notation, $\forall\ \epsilon_r \in \epsilon \subset E,\ \exists \text{ corresponding } a_{\epsilon_r} \in A_{\epsilon} \subset A$. Thus, it follows that the subset $A_{\epsilon} \subset A$ represents the distances between each adjacent node within the set $K \in V$, $\forall\ v_i \in V$ and $\forall\ \mathscr f_z \in F_p$, hence $$\delta (v_i,\mathscr f_z) = \sum_{r=1}^{q-1} a_{\epsilon_r}= \sum_{r=1}^{q-1} \varepsilon_r (v_i,\mathscr f_z)$$ leading to $$\psi (v_i) = w_i \cdot \min_{\mathscr f_z \in F_p} \sum_{r=1}^{q-1} \varepsilon_r (v_i,\mathscr f_z)$$ and thus $$\Gamma (F_p) = \sum_{\mathscr f_z \in F_p} \gamma (\mathscr f_z) + \sum_{v_i \in V} w_i \cdot \min_{\mathscr f_z \in F_p} \sum_{r=1}^{q-1} \varepsilon_r (v_i,\mathscr f_z)$$
</p>
<p>
Let $\xi$ denote the sum of all $\varepsilon$ for given $v_i,\mathscr f_z$: $$\xi (v_i,\mathscr f_z) = \sum_{r=1}^{q-1} \varepsilon_r (v_i,\mathscr f_z) $$
Our objective function has now become $$\Gamma (F_p) = \sum_{\mathscr f_z \in F_p} \gamma (\mathscr f_z) + \sum_{v_i \in V} w_i \cdot \xi (v_i,\mathscr f_z) $$
Finally, because there exists a one-to-one correspondence between $v_i \in V \text{ and } i=1,2,\cdots,n$ as well as between $\mathscr f_z \in F_p \text{ and } z=1,2,\cdots,n$


<br>






<h1>References:</h1>
<p id="section1">[i] "(PDF) A New Template for Solving p-Median Problems for Trees in Sub-Quadratic Time." ResearchGate. Accessed April 22, 2019. <cite>https://www.researchgate.net/publication/220770539_A_New_Template_for_Solving_p-Median_Problems_for_Trees_in_Sub-quadratic_Time</cite>.</p>
<p id="section2">[ii] For simplicity, by the term "tree-metric distance" here, we are meaning to say that the distance between any two nodes of $T$ is given by the "tree-path" distance described by the topology of the tree itself.
